<a href="https://colab.research.google.com/github/Christina-26/Marvel-tasks-level-1/blob/main/task_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#1D ARRAY
#list
a = np.array([1,2,3,4,5])
#tuple
b = np.array((1,2,3,4,5))
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [12]:
# 2D ARRAY using tuple
a2 = np.array([(1,2,3),(4,5,6)])
print(a2)

[[1 2 3]
 [4 5 6]]


In [4]:
#2D ARRAY using list
b2 = np.array([[12,23,34],[45,56,67]])
print(b2)

[[12 23 34]
 [45 56 67]]


In [20]:
#checking dimension of array
b2.ndim

2

In [7]:
a.ndim

1

In [13]:
a2.ndim

2

In [16]:
#3D ARRAY using tuple
a3 = np.array([((1,2,3),(4,5,6)),((7,8,9),(1,2,3))])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [17]:
a3.ndim

3

In [19]:
#accessing array elements
a3[0][0][1]

2

In [24]:
#creating a array by repeating small array of 1D
a = np.array([1,2,3,4,5])
newarray = np.repeat(a,3,axis=0)
print(newarray)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [23]:
#creating a array by repeating small array of 2D
newarrayy = np.repeat(a2,4,axis=1)
print(newarrayy)

[[1 1 1 1 2 2 2 2 3 3 3 3]
 [4 4 4 4 5 5 5 5 6 6 6 6]]


In [25]:
#creating a array by repeating small array of 3D
newarr = np.repeat(a3,5,axis = 2)
print(newarr)

[[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]
  [4 4 4 4 4 5 5 5 5 5 6 6 6 6 6]]

 [[7 7 7 7 7 8 8 8 8 8 9 9 9 9 9]
  [1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]]]


In [27]:
#Generate an array with element indexes such that the array elements appear in ascending order
arraysize = 5
elements = np.argsort(np.arange(arraysize))
print(elements)

[0 1 2 3 4]
